### PR TITLE
update runtime to version 5.15-22.08

### PR DESCRIPTION
**Pull request by christianrauch**

### CODE REVIEW

**Comment by ddennedy** [comment]
Does this fix or improve something for you? It did not fix https://github.com/mltframework/shotcut/issues/1405

**Comment by christianrauch** [comment]
> Does this fix or improve something for you?

Yes. It reduces the number of runtimes required to be installed on my system.

> It did not fix [mltframework/shotcut#1405](https://github.com/mltframework/shotcut/issues/1405)

I did not try to resolve this issue. As far as I can tell, the issue was already closed 3 weeks ago. What makes you think I wanted to fix this issue? :-)

**Comment by ddennedy** [comment]
I do not like to change things between releases without a very good reason, and reducing runtimes on your system is not one of them. Work on the next version is in #69 and already changes runtime version.

**Comment by christianrauch** [comment]
> Work on the next version is in #69 and already changes runtime version.

There are two Draft PRs changing the runtime to Qt 6. Is one of them going to be merged soon? I am asking because they were created 2 months ago.

> I do not like to change things between releases without a very good reason, and reducing runtimes on your system is not one of them.

Well, that's the reason why I send the PR. But there will be others that will benefit from this too, of course.

`5.15-22.08` is the latest Qt 5.15 runtime. Everyone that is using multiple apps that depend on Qt 5.15 will benefit from the reduced number of runtimes and space requirements. If the Qt 6 release takes much longer, I think there is a benefit for all Shotcut users that also use other Qt 5 apps.

**Pull request closed without merging**
