### PR TITLE
update LinuxAudio (LADSPA) runtime to 23.08

### LINKED ISSUE #117: Shotcut is using deprecated org.freedesktop.Platform.GL
I have two installations of Shotcut as flatpak and they are referencing EOL'd runtime components:

fedora Silverblue 41 Beta:
org.freedesktop.LinuxAudio.Plugins.swh/x86_64/22.08

fedora Worksation 40 Cinnamon spin:
org.freedesktop.LinuxAudio.Plugins.swh/x86_64/22.08
org.freedesktop.Platform.GL.default/x86_64/22.08
org.freedesktop.Platform.GL.default/x86_64/22.08-extra

The application runtime itself has been kept current but these helper runtimes are lagging behind.

### PR DESCRIPTION
**Pull request by ddennedy**
partially fixes #117

### CODE REVIEW

**Comment by hfiguiere** [comment]
no. There is no Qt runtime based on 24.08.

**Comment by hfiguiere** [comment]
6.7 is based on 23.08

**Comment by ddennedy** [comment]
With this change there are no SWH LADSPA plugins included. I reviewed the build log, and it does build and include the base LADSPA SDK with example plugins in `/app/lib/ladpsa` but nothing for SWH, which is what we use. The only mention of "swh" in the build log is in this flatpak command line:
`FB: Running: flatpak build-finish --command=shotcut --require-version=0.11.4 --share=ipc --socket=x11 --device=all --share=network --filesystem=host --socket=pulseaudio --filesystem=xdg-run/pipewire-0 --env=FREI0R_PATH=/app/lib/frei0r-1 --env=LADSPA_PATH=/app/extensions/Plugins/ladspa:/app/lib/ladspa --env=QT_QUICK_CONTROLS_CONF=:/resources/qtquickcontrols2-dark.conf --extension=org.freedesktop.LinuxAudio.Plugins=directory=extensions/Plugins --extension=org.freedesktop.LinuxAudio.Plugins=no-autodownload=true --extension=org.freedesktop.LinuxAudio.Plugins=subdirectories=true --extension=org.freedesktop.LinuxAudio.Plugins=add-ld-path=lib --extension=org.freedesktop.LinuxAudio.Plugins=merge-dirs=ladspa --extension=org.freedesktop.LinuxAudio.Plugins=version=23.08 --extension=org.freedesktop.LinuxAudio.Plugins.swh=directory=extensions/Plugins/swh --extension=org.freedesktop.LinuxAudio.Plugins.swh=subdirectories=true --extension=org.freedesktop.LinuxAudio.Plugins.swh=add-ld-path=lib --extension=org.freedesktop.LinuxAudio.Plugins.swh=merge-dirs=ladspa --extension=org.freedesktop.LinuxAudio.Plugins.swh=version=23.08 /srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-OG6MhX`

**Comment by hfiguiere** [comment]
they have to be installed. They get installed automatically when installing the package. Not when building. The existing //22.08 will not be used.

**Comment by ddennedy** [comment]
Thanks, Hubert. But not installed automatically when installing the test package. Manually installed with `flatpak install org.freedesktop.LinuxAudio.Plugins.swh//23.08` and confirmed it is working.

**Comment by hfiguiere** [comment]
test packages might also be a corner case. I do believe `flatpak update` might have installed it afterwards.

**Pull request merged**
