### PR TITLE
Revert "disable wayland, fixes #19"

### LINKED ISSUE #19: windows decoration missing on Wayland
https://forum.shotcut.org/t/shotcut-flatpak-windows-decoration-missing-on-wayland/16516

> Hello everybody.
> I installed shotcut via flatpak on PopOs 19.10 (gnome 3.34.2). The installation process, after downloading some runtimes, went well without obvious problems. Once I launched the application, however, I encountered the following problem: the window decoration is not displayed correctly. The maximize, minimize, close buttons are missing. The full screen display doesn’t work and the window can’t be resized. What’s worse is that the various bars that can be “detached and repositioned” typical of kde plasma, once “detached” from the main window are not manageable because they miss the decoration and can no longer be reattached.
> 
> This is all happening using Wayland. Ending the session and returning to Xorg everything works perfectly.
> 
> Unfortunately I only started using flatpaks these days and I have no idea if and how it is possible to run software on Wayland in x11 compatible mode.
> 
> Does anyone have any idea? I’d prefer to keep using Wayland, not only because it’s more modern but especially because of the great support for multitouch gestures (macOs level by the way), something that xorg is not even remotely able to replicate.

### PR DESCRIPTION
**Pull request by ddennedy**
This reverts commit 7c1bac40b95e1c02332a975054d3eabd1b72081a.

### CODE REVIEW

**Comment by ddennedy** [comment]
This build is working for me on a non-Wayland system.

**Comment by hfiguiere** [comment]
but are things working on Wayland? My experience with Qt5 and Wayland is *too many bugs*, at least when running with GNOME-shell.

**Comment by ddennedy** [comment]
I do not have a wayland machine ready to try, and I need to rely upon some others for now until I get around to it. Feedback is appreciated.

**Comment by timlau** [comment]
Made a local flatpak build on my Fedora system build & run it with
`
flatpak-builder --force-clean .build org.shotcut.Shotcut.yaml
flatpak-builder --run  .build org.shotcut.Shotcut.yaml shotcut
`
, changed --nosocket wayland to --socket wayland

run it with
`
flatpak-builder --force-clean .build org.shotcut.Shotcut.yaml
flatpak-builder --run  .build org.shotcut.Shotcut.yaml shotcut
`

Both version is running without any issues.

[Screenshot from 2022-01-26 16-25-01](https://user-images.githubusercontent.com/283985/151192952-9c2b28dc-834d-4894-a690-fd7b75cb3bc9.png)

**Comment by ddennedy** [comment]
Thank you @timlau !

**Comment by timlau** [comment]
Upgraded shotcut from flathub on another wayland machine this morning, And it is working fine.

shotcut_wayland

**Pull request merged**
