### PR TITLE
version 22.03.30

### PR DESCRIPTION
**Pull request by ddennedy**

### CODE REVIEW

**Comment by ddennedy** [comment]
The newer runtime version does not work for me either and crashes in the same place/way.

**Comment by timlau** [comment]
Same issue, drag form play crash, but everything else works fine.

**Comment by timlau** [comment]
maybe adding - --nosocket=wayland is the best for now, until ready shotcut move to qt6 or the issues with qt5 in a flatpak sandbox on wayland is solved.

**Comment by ddennedy** [comment]
I reverted the runtime version and removed the wayland socket, and it still crashes upon startup for me. I will not be releasing this new version as flatpak as long as it is crashing for me.

**Comment by timlau** [comment]
I have tested the latest flatpak build on my Fedora Linux 36 and on a  fresh Ubuntu 21.10 installation in a virtual machine.
Both are running fine, no crashes when dragging video from playlist to timeline.

What distro are you testing on ?

**Comment by ddennedy** [comment]
I am on Ubuntu 20.04. See PR #54 where I committed and tested each small change incrementally. It fails when updating Shotcut.  Finally, I had the idea to clear my configuration, and that fixed it! I know we devs and others have recommended trying this to others especially on Windows, but this is the first time I have ever needed it regardless of OS.

**Pull request closed without merging**
