### PR TITLE
shotcut 21.05.01

### LINKED ISSUE #36: Update available 21.05.1
https://www.shotcut.org/blog/new-release-210501/

### PR DESCRIPTION
**Pull request by hfiguiere**
Also fix JACK support for flatpak using Pipewire.

Close #36

### CODE REVIEW

**Comment by hfiguiere** [comment]
It still crashes.

**Comment by ddennedy** [comment]
Are you saying it still crashes even after building with the MLT fix in https://github.com/mltframework/mlt/commit/d0ff2b5a6586ddc0a0509c016ae56bdb80741034 ? When does it crash? launch?

**Comment by hfiguiere** [comment]
> Are you saying it still crashes even after building with the MLT fix in [mltframework/mlt@d0ff2b5](https://github.com/mltframework/mlt/commit/d0ff2b5a6586ddc0a0509c016ae56bdb80741034) ? When does it crash? launch?

Before that it crashed when creating a new project (there was none open).

When I open the existing project I created:
```

Thread 17 "shotcut" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd37ee700 (LWP 24)]
0x0000555555620f40 in ?? ()
(gdb) where
#0  0x0000555555620f40 in  ()
#1  0x00007ffff7f52079 in mlt_events_fire () at /app/lib/libmlt-7.so.7
#2  0x00007fffc52a3000 in  () at /app/lib/mlt-7/libmltjackrack.so
#3  0x00007fffc52576ec in cycle_run () at /usr/lib/x86_64-linux-gnu/libjack.so.0
#4  0x00007fffc5267363 in on_rtsocket_condition () at /usr/lib/x86_64-linux-gnu/libjack.so.0
#5  0x00007fffe801f063 in loop_iterate () at /usr/lib/x86_64-linux-gnu/spa-0.2/support/libspa-support.so
#6  0x00007fffc51c7517 in do_loop () at /usr/lib/x86_64-linux-gnu/libpipewire-0.3.so.0
#7  0x00007ffff5c324d2 in start_thread () at /usr/lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007ffff57fd323 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6
```

Or when I open video in a new project. (similar stack trace)

**Comment by ddennedy** [comment]
Your reply is unclear. I do not care about before. I am asking about now, latest flatpak build of 21.05.01. Is that stack trace for latest? If so, try removing your shotcut config file to be sure it does not use JACK audio. Also you can try simply removing libmltjackrack.so.

**Comment by hfiguiere** [comment]
Before is when I built with the mlt `v7.0.0` tag. After is the current commit which is `f4ce00681c36f785ddce4c525322e0b0b00d54b8`

**Comment by hfiguiere** [comment]
I didn't submit the PR when building with `v7.0.0`.

**Comment by ddennedy** [comment]
I understand before and after. What I do not understand is which version was used for the stack trace above. You wrote "Before..." followed by a stack trace. I can only assume that stack trace is from before.

I ran the command listed above in this PR `flatpak install --user https://dl.flathub.org/build-repo/45447/org.shotcut.Shotcut.flatpakref` and it works for me not using JACK audio. When using JACK, I reproduced a bug (in Shotcut's code) similar to your stack trace that is new and not yet published or fixed.

**Comment by hfiguiere** [comment]
Ah right I had JACK enabled as I wanted to test.

I can cherry-pick that patch for the build.

**Comment by hfiguiere** [comment]
This works better. Thanks @ddennedy !

**Comment by hfiguiere** [comment]
@eszlari good to merge?

**Comment by ddennedy** [comment]
Unfortunately, Pete has become unresponsive and inactive since late April. I even sent e-mail that went unanswered. I fear something unfortunate has happened, or he decided to quit working on FOSS. Do you have permission to commit?

**Comment by hfiguiere** [comment]
fortunately I do have. I just prefer not step on other people's toes.

Merged.
Thanks for the help!

**Pull request merged**
