### PR TITLE
Build on aarch64

### PR DESCRIPTION
**Pull request by hfiguiere**
On top the qt6 branch, I built for aarch64. it start on a RaspberryPi and seems to be able to playback videos.

(it didn't build with Qt 5.15 last time I tried)

Making this as a draft.

### CODE REVIEW

**Comment by eszlari** [comment]
@ddennedy Note that you can commit directly to the "beta" branch to make the binaries permanently avaiable from the beta repo:

https://discourse.flathub.org/t/how-to-use-flathub-beta/2111

**Comment by ddennedy** [comment]
@eszlari beta branch of what? Those instructions are about using betas, not about publishing betas. Also, reading all of that and trying to understand and follow it is more difficult for users than the single line shown in the Build successful message here. It does not matter as I plan to merge the flatpak ahead of release to address a major issue in Qt 5.15.8 that we cannot fix.

**Comment by hfiguiere** [comment]
whenever you feel it's ready.

**Comment by eszlari** [comment]
> @eszlari beta branch of what?

The beta branch of this Flatpak manifest here on Flathub:
https://github.com/flathub/org.shotcut.Shotcut/tree/beta

**Pull request merged**
