### PR TITLE
Upgrade shotcut 21.05.18

### PR DESCRIPTION
**Pull request by ddennedy**

### CODE REVIEW

**Comment by hfiguiere** [comment]
BTW, since you are upstream contributor, do you want write access to this repository?

**Comment by ddennedy** [comment]
yes, please

**Comment by hfiguiere** [comment]
@barthalion or @nedrichards can you invite @ddennedy to this repository? Thanks.

**Comment by barthalion** [comment]
Done, you should be able to accept it at https://github.com/flathub/org.shotcut.Shotcut/invitations.

**Pull request merged**
